create table SCREENCONFIG
( 
id raw(16) DEFAULT sys_guid() PRIMARY KEY,
TagName varchar2(100),
NameAddress NUMBER(1) DEFAULT 0 NOT NULL,
CountryAndCity NUMBER(1) DEFAULT 0 NOT NULL,
Goods NUMBER(1) DEFAULT 0 NOT NULL,
Narrative NUMBER(1) DEFAULT 0 NOT NULL,
BicCode NUMBER(1) DEFAULT 0 NOT NULL,
Port NUMBER(1) DEFAULT 0 NOT NULL,
ValidFlag NUMBER(1) DEFAULT 0 NOT NULL,
CreateUser varchar2(10),
CreateDatetime Timestamp DEFAULT CURRENT_TIMESTAMP,
UpdateUser varchar2(10),
UpdateDatetime Timestamp
);

CREATE INDEX MEGA_ECM.SCREENCONFIG_TAGNAME_INDEX ON MEGA_ECM.SCREENCONFIG (TAGNAME ASC, VALIDFLAG DESC);
CREATE INDEX MEGA_ECM.SCREENCONFIG_VALIDFLAG_INDEX ON MEGA_ECM.SCREENCONFIG (VALIDFLAG DESC);

