
DROP TABLE MEGA_ECM.TF_CASE_AUDITS;
DROP INDEX MEGA_ECM.TF_CASE_AUDITS_ValidFlag_INDEX;
DROP INDEX MEGA_ECM.TF_CASE_AUDITS_CaseId_INDEX;

CREATE TABLE MEGA_ECM.TF_CASE_AUDITS (
    Id raw(16) DEFAULT sys_guid() PRIMARY KEY,
    CaseId raw(16),
    UserComment varchar2(4000),
    CaseStatusCode NUMBER(3, 0),
    ValidFlag NUMBER(1) DEFAULT 0 NOT NULL,
    CreateUser varchar2(10) NOT NULL,
    CreateDatetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdateUser varchar2(10),
    UpdateDatetime TIMESTAMP
);
CREATE INDEX MEGA_ECM.TF_CASE_AUDITS_ValidFlag_INDEX ON MEGA_ECM.TF_CASE_AUDITS (ValidFlag DESC);
CREATE INDEX MEGA_ECM.TF_CASE_AUDITS_CaseId_INDEX ON MEGA_ECM.TF_CASE_AUDITS (CaseId DESC);
commit;