DROP TABLE MEGA_ECM.TF_ALERT_LIST_DETAIL;

CREATE TABLE MEGA_ECM.TF_ALERT_LIST_DETAIL (
	AlertID raw(16),
	ListSubTypeID VARCHAR2(40 CHAR),
	ListRecord CLOB
	);

CREATE INDEX MEGA_ECM.TF_ALERT_LIST_DETAIL_AlertID_ListSubTypeID_INDEX ON MEGA_ECM.TF_ALERT_LIST_DETAIL (
	AlertID DESC,
	ListSubTypeID DESC
	);

COMMIT;
