
DROP TABLE MEGA_ECM.TF_CASES_COMMENTS;

CREATE TABLE MEGA_ECM.TF_CASES_COMMENTS (
    Id raw(16) DEFAULT sys_guid() PRIMARY KEY,
    CaseId raw(16),
    UserComment varchar2(4000),
    CaseStatusCode NUMBER(3, 0),
    ValidFlag NUMBER(1) DEFAULT 0 NOT NULL,
    CreateUser varchar2(10) NOT NULL,
    CreateDatetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdateUser varchar2(10),
    UpdateDatetime TIMESTAMP
);
CREATE INDEX MEGA_ECM.TF_CASES_COMMENTS_ValidFlag_INDEX ON MEGA_ECM.TF_CASES_COMMENTS (ValidFlag DESC);
CREATE INDEX MEGA_ECM.TF_CASES_COMMENTS_CaseId_INDEX ON MEGA_ECM.TF_CASES_COMMENTS (CaseId DESC);
commit;