DROP TABLE MEGA_ECM.ScreenSubConfig;
create table ScreenSubConfig (
    id raw(16) DEFAULT sys_guid() PRIMARY KEY,
    ScreenConfigId raw(16),
    MessageSourceCode NUMBER(3, 0),
    TagName varchar2(100),
    EntityType varchar2(2),
    NameAddress NUMBER(1) DEFAULT 0 NOT NULL,
    CountryAndCity NUMBER(1) DEFAULT 0 NOT NULL,
    Goods NUMBER(1) DEFAULT 0 NOT NULL,
    Narrative NUMBER(1) DEFAULT 0 NOT NULL,
    BicCode NUMBER(1) DEFAULT 0 NOT NULL,
    Port NUMBER(1) DEFAULT 0 NOT NULL,
    ValidFlag NUMBER(1) DEFAULT 0 NOT NULL,
    CreateUser varchar2(10),
    CreateDatetime Timestamp DEFAULT CURRENT_TIMESTAMP,
    UpdateUser varchar2(10),
    UpdateDatetime Timestamp
);

CREATE INDEX MEGA_ECM.ScreenSubConfig_TAGNAME_INDEX ON MEGA_ECM.ScreenSubConfig (TAGNAME ASC, VALIDFLAG DESC);
CREATE INDEX MEGA_ECM.ScreenSubConfig_MESSAGESOURCECODE_TAGNAME_ENTITYTYPE_INDEX ON MEGA_ECM.ScreenSubConfig (
    MESSAGESOURCECODE ASC,
    TAGNAME ASC,
    ENTITYTYPE ASC,
    VALIDFLAG DESC
);
CREATE INDEX MEGA_ECM.ScreenSubConfig_VALIDFLAG_INDEX ON MEGA_ECM.ScreenSubConfig (VALIDFLAG DESC);

Insert into MEGA_ECM.ScreenSubConfig (ScreenConfigId,MESSAGESOURCECODE,TAGNAME,ENTITYTYPE,NAMEADDRESS,COUNTRYANDCITY,GOODS,NARRATIVE,BICCODE,PORT,VALIDFLAG,CREATEUSER) values ('CA3482441B5A19B2E0531336A8C0FE2A',1,'english_name',null,1,0,0,0,0,0,1,'008958');
Insert into MEGA_ECM.ScreenSubConfig (ScreenConfigId,MESSAGESOURCECODE,TAGNAME,ENTITYTYPE,NAMEADDRESS,COUNTRYANDCITY,GOODS,NARRATIVE,BICCODE,PORT,VALIDFLAG,CREATEUSER) values ('CA3482441B5A19B2E0531336A8C0FE2A',1,'english_name','05',0,1,0,0,0,1,1,'008958');
Insert into MEGA_ECM.ScreenSubConfig (ScreenConfigId,MESSAGESOURCECODE,TAGNAME,ENTITYTYPE,NAMEADDRESS,COUNTRYANDCITY,GOODS,NARRATIVE,BICCODE,PORT,VALIDFLAG,CREATEUSER) values ('CA3482441B5A19B2E0531336A8C0FE2A',1,'english_name','07',0,0,1,0,0,0,1,'008958');

commit;